### ISSUE TITLE
Typo's in the ReadMe

### ISSUE THREAD

**Issue by Timmoth** [andresantarosa/CleanArchitectureExample#1]
I have just seen your post on Reddit, It's come at a great time for me as I've just started using Asp.net Core WebApi. I'll be studying your code in detail over the next week or so. 
For now I've spotted these typo's in the ReadMe. 

> In this project were **applied** the concepts of:

> Suggestions for improvements are very welcome and if you **find any** bugs or have any **questions** just open an Issue and I'll take a look as soon as possible =)

Great work though, I've starred for future use!

**Comment by andresantarosa** [comment]
Hello, Timmoth! Thanks for the reporting the typos, I fixed them in this new batch of adjusts.

Any questions, suggestions or bugs found, just open a new issue =)
